version: 2.1
# Use a package of configuration called an orb.
jobs:
  circleci_test:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - run: mvn install
    - run: mvn package
    
    
workflows:
  version: 2
  build:
    jobs:
      - circleci_test:
          filters:
            branches:
              only: circleci-project-setup
